name: 'Stream Deck Distribution Tool'
author: 'AdamCarballo'
branding:
  icon: 'layers'
  color: 'blue'
description: 'DESCRIPTION'
inputs:
  input:
    description: 'DESCRIPTION'
    required: true
  output:
    description: 'DESCRIPTION'
    required: false
    default: ''
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/main.sh ${{ inputs.input }} ${{ inputs.output }} ${{ github.workspace }} ${{ runner.os }}
      shell: bash